name: Build Geode Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
          - name: macOS
            os: macos-latest
          - name: iOS
            os: macos-latest
            target: iOS
          - name: Android32
            os: ubuntu-latest
            target: Android32
          - name: Android64
            os: ubuntu-latest
            target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Geode
        uses: geode-sdk/setup-geode@main

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.config.target }}
          combine: true

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - name: Merge Platforms
        uses: geode-sdk/build-geode-mod/combine@main

      - name: Upload Universal File
        uses: actions/upload-artifact@v4
        with:
          name: Level-Generator-Universal
          path: geode
